# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class CandlePattern(BaseModel):
    type: typing.Optional[str] = Field(default=None, description='e.g. Hammer, Shooting Star, Bullish Engulfing, Bearish Engulfing, Doji, Marubozu, Morning Star, Evening Star, Spinning Top')
    location: typing.Optional[str] = Field(default=None, description='Position on chart: bottom-of-range, top-of-range, mid-range, at-support, at-resistance')
    strength: typing.Optional[typing.Union[typing_extensions.Literal['Strong'], typing_extensions.Literal['Moderate'], typing_extensions.Literal['Weak']]] = None
    is_valid: typing.Optional[bool] = Field(default=None, description='True ONLY if the pattern has structural confluence. A Hammer at mid-range is FALSE. A Hammer at the bottom of a 20-candle downmove is TRUE.')
    context: typing.Optional[str] = Field(default=None, description='1-2 sentences: why valid, or why discounted. Be specific.')

class ChartShape(BaseModel):
    pattern: typing.Optional[str] = Field(default=None, description='Double Top, Double Bottom, Head and Shoulders, Inverse H&S, Bull Flag, Bear Flag, Ascending/Descending Triangle, Wedge, Channel, Cup & Handle')
    status: typing.Optional[typing.Union[typing_extensions.Literal['Forming'], typing_extensions.Literal['Confirmed'], typing_extensions.Literal['Broken']]] = None
    implication: typing.Optional[str] = Field(default=None, description='What this pattern means for near-term price direction')

class FairValueGap(BaseModel):
    direction: typing.Optional[typing.Union[typing_extensions.Literal['Bullish'], typing_extensions.Literal['Bearish']]] = Field(default=None, description='Bullish FVG = price likely to fill up; Bearish FVG = price likely to fill down')
    description: typing.Optional[str] = Field(default=None, description='Location description, approximate price level if legible, and gap size (small/medium/large)')

class TradingCoachOutput(BaseModel):
    candle_patterns: typing.List["CandlePattern"] = Field(description='ALL identifiable patterns including discounted ones — show your work')
    market_phase: typing.Optional[types.MarketPhase] = None
    phase_explanation: typing.Optional[str] = Field(default=None, description='2-3 sentences of hard evidence for the market phase call')
    chart_shapes: typing.List["ChartShape"] = Field(description='Geometric patterns visible, or empty array if none')
    fair_value_gaps: typing.List["FairValueGap"] = Field(description='FVGs and liquidity voids identified, or empty array if none')
    zoom_assessment: typing.Optional["ZoomInstruction"] = None
    coach_commentary: typing.Optional[str] = Field(default=None, description='Your main coaching insight. Use veteran trader language. Be direct, tactical, and specific. No fluff.')
    call_to_action: typing.Optional[str] = Field(default=None, description='The single most important thing the trader should do RIGHT NOW. One sentence.')
    bias: typing.Optional[typing.Union[typing_extensions.Literal['Bullish'], typing_extensions.Literal['Bearish'], typing_extensions.Literal['Neutral']]] = None
    confidence: typing.Optional[typing.Union[typing_extensions.Literal['High'], typing_extensions.Literal['Medium'], typing_extensions.Literal['Low']]] = None

class ZoomInstruction(BaseModel):
    state: typing.Optional[typing.Union[typing_extensions.Literal['TooZoomedIn'], typing_extensions.Literal['Optimal'], typing_extensions.Literal['TooZoomedOut']]] = None
    estimated_candles: typing.Optional[int] = Field(default=None, description='Rough estimate of visible candles on chart')
    coaching_message: typing.Optional[str] = Field(default=None, description='Explain WHY the current zoom level is a problem or is good. Reference the candle count.')
    call_to_action: typing.Optional[str] = Field(default=None, description='Specific instruction: e.g. \'Switch to the 4H chart to see the supply zone you are currently hitting from below\' or \'Zoom to 15m to confirm the entry trigger candle\'')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
