# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class MarketPhase(str, Enum):
    Accumulation = "Accumulation"
    Manipulation = "Manipulation"
    Distribution = "Distribution"
    Expansion = "Expansion"

# #########################################################################
# Generated classes (5)
# #########################################################################

class CandlePattern(BaseModel):
    type: str = Field(description='e.g. Hammer, Shooting Star, Bullish Engulfing, Bearish Engulfing, Doji, Marubozu, Morning Star, Evening Star, Spinning Top')
    location: str = Field(description='Position on chart: bottom-of-range, top-of-range, mid-range, at-support, at-resistance')
    strength: typing.Union[typing_extensions.Literal['Strong'], typing_extensions.Literal['Moderate'], typing_extensions.Literal['Weak']]
    is_valid: bool = Field(description='True ONLY if the pattern has structural confluence. A Hammer at mid-range is FALSE. A Hammer at the bottom of a 20-candle downmove is TRUE.')
    context: str = Field(description='1-2 sentences: why valid, or why discounted. Be specific.')

class ChartShape(BaseModel):
    pattern: str = Field(description='Double Top, Double Bottom, Head and Shoulders, Inverse H&S, Bull Flag, Bear Flag, Ascending/Descending Triangle, Wedge, Channel, Cup & Handle')
    status: typing.Union[typing_extensions.Literal['Forming'], typing_extensions.Literal['Confirmed'], typing_extensions.Literal['Broken']]
    implication: str = Field(description='What this pattern means for near-term price direction')

class FairValueGap(BaseModel):
    direction: typing.Union[typing_extensions.Literal['Bullish'], typing_extensions.Literal['Bearish']] = Field(description='Bullish FVG = price likely to fill up; Bearish FVG = price likely to fill down')
    description: str = Field(description='Location description, approximate price level if legible, and gap size (small/medium/large)')

class TradingCoachOutput(BaseModel):
    candle_patterns: typing.List["CandlePattern"] = Field(description='ALL identifiable patterns including discounted ones — show your work')
    market_phase: MarketPhase
    phase_explanation: str = Field(description='2-3 sentences of hard evidence for the market phase call')
    chart_shapes: typing.List["ChartShape"] = Field(description='Geometric patterns visible, or empty array if none')
    fair_value_gaps: typing.List["FairValueGap"] = Field(description='FVGs and liquidity voids identified, or empty array if none')
    zoom_assessment: "ZoomInstruction"
    coach_commentary: str = Field(description='Your main coaching insight. Use veteran trader language. Be direct, tactical, and specific. No fluff.')
    call_to_action: str = Field(description='The single most important thing the trader should do RIGHT NOW. One sentence.')
    bias: typing.Union[typing_extensions.Literal['Bullish'], typing_extensions.Literal['Bearish'], typing_extensions.Literal['Neutral']]
    confidence: typing.Union[typing_extensions.Literal['High'], typing_extensions.Literal['Medium'], typing_extensions.Literal['Low']]

class ZoomInstruction(BaseModel):
    state: typing.Union[typing_extensions.Literal['TooZoomedIn'], typing_extensions.Literal['Optimal'], typing_extensions.Literal['TooZoomedOut']]
    estimated_candles: int = Field(description='Rough estimate of visible candles on chart')
    coaching_message: str = Field(description='Explain WHY the current zoom level is a problem or is good. Reference the candle count.')
    call_to_action: str = Field(description='Specific instruction: e.g. \'Switch to the 4H chart to see the supply zone you are currently hitting from below\' or \'Zoom to 15m to confirm the entry trigger candle\'')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
