# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CandlePattern": types.CandlePattern,
    "stream_types.CandlePattern": stream_types.CandlePattern,

    "types.ChartShape": types.ChartShape,
    "stream_types.ChartShape": stream_types.ChartShape,

    "types.FairValueGap": types.FairValueGap,
    "stream_types.FairValueGap": stream_types.FairValueGap,

    "types.TradingCoachOutput": types.TradingCoachOutput,
    "stream_types.TradingCoachOutput": stream_types.TradingCoachOutput,

    "types.ZoomInstruction": types.ZoomInstruction,
    "stream_types.ZoomInstruction": stream_types.ZoomInstruction,


    "types.MarketPhase": types.MarketPhase,

}